name: Build FFmpeg Static

on:
  push:
    tags:
      - "v*"   # 打 tag 时触发，比如 v7.1
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: windows-latest
            arch: x86_64
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64

    steps:
      - name: Checkout FFmpeg source
        uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: master   # 或者指定 tag

      # Linux 依赖
      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y yasm nasm pkg-config build-essential

      # macOS 依赖
      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install yasm nasm

      # Windows 依赖
      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install make nasm yasm

      - name: Configure FFmpeg
        run: |
          ./configure \
            --enable-static \
            --disable-shared \
            --disable-programs \
            --disable-doc \
            --disable-debug \
            --prefix=$PWD/build
        shell: bash

      - name: Build
        run: make -j$(nproc)
        shell: bash

      - name: Install
        run: make install
        shell: bash

      - name: Package
        run: |
          cd build
          zip -r ../ffmpeg-${{ matrix.os }}-${{ matrix.arch }}.zip *
        shell: bash

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ffmpeg-${{ matrix.os }}-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
